### ISSUE TITLE
Add option to include `languages contributed` to stats

### ISSUE THREAD

**Issue by RealRichi3** [andrii-bodnar/action-crowdin-contributors#53]
## Summary
Currently the action doesn't include the languages contributed.

There should be feature to allow optional inclusion of the languages contributed by the crowdin contributors. I know it might take up more space when the number of languages are much, so we can use the language abbreviations (three letters max) instead then at the footer we can add something like a reference for the language abbreviations and their full form.

**Comment by RealRichi3** [comment]
I think i can work on this if approved

**Comment by andrii-bodnar** [comment]
Hi @RealRichi3, it would be awesome!

Actually, I've already done some work on this and pushed it to the [`feat/include_languages-option`](https://github.com/andrii-bodnar/action-crowdin-contributors/tree/feat/include_languages-option) branch.

The only thing left is to finish the Unit tests for the Writer class

**Comment by RealRichi3** [comment]
perfect, thanks @andrii-bodnar

**Comment by RealRichi3** [comment]
Thanks for everything @andrii-bodnar, i guess there isn't much to do since you're almost done, let me know if there's any way i can assist. Thanks

**Comment by andrii-bodnar** [comment]
@RealRichi3 it would be great if you could help with writing tests and validating if everything works as expected. thanks
